import 'dart:convert';
import 'package:http/http.dart' as http;

class Country {
  final String name;

  const Country({required this.name});
}

class CountryService {
  static const _url = 'https://restcountries.com/v3.1/all?fields=name,flag';
  static List<Country>? _cache;

  Future<List<Country>> fetchCountries() async {
    if (_cache != null) return _cache!;

    try {
      final response = await http
          .get(Uri.parse(_url))
          .timeout(const Duration(seconds: 8));

      if (response.statusCode == 200) {
        final List<dynamic> data = jsonDecode(response.body);
        final countries = data.map((e) {
          final nameObj = e['name'] as Map<String, dynamic>;
          return Country(
            name: nameObj['common'] as String? ?? '',
            
          );
        }).where((c) => c.name.isNotEmpty).toList()
          ..sort((a, b) => a.name.compareTo(b.name));
        _cache = countries;
        return countries;
      }
    } catch (_) {
      // Fall through to bundled list
    }

    // ── Bundled fallback (used when network/CORS is unavailable) ──────
    _cache = _bundled;
    return _bundled;
  }
}

// 195 UN member states — sorted alphabetically with emoji flags.
const List<Country> _bundled = [
 Country(name: 'Afghanistan'),
Country(name: 'Albania'),
Country(name: 'Algeria'),
Country(name: 'Andorra'),
Country(name: 'Angola'),
Country(name: 'Antigua and Barbuda'),
Country(name: 'Argentina'),
Country(name: 'Armenia'),
Country(name: 'Australia'),
Country(name: 'Austria'),
Country(name: 'Azerbaijan'),
Country(name: 'Bahamas'),
Country(name: 'Bahrain'),
Country(name: 'Bangladesh'),
Country(name: 'Barbados'),
Country(name: 'Belarus'),
Country(name: 'Belgium'),
Country(name: 'Belize'),
Country(name: 'Benin'),
Country(name: 'Bhutan'),
Country(name: 'Bolivia'),
Country(name: 'Bosnia and Herzegovina'),
Country(name: 'Botswana'),
Country(name: 'Brazil'),
Country(name: 'Brunei'),
Country(name: 'Bulgaria'),
Country(name: 'Burkina Faso'),
Country(name: 'Burundi'),
Country(name: 'Cabo Verde'),
Country(name: 'Cambodia'),
Country(name: 'Cameroon'),
Country(name: 'Canada'),
Country(name: 'Central African Republic'),
Country(name: 'Chad'),
Country(name: 'Chile'),
Country(name: 'China'),
Country(name: 'Colombia'),
Country(name: 'Comoros'),
Country(name: 'Congo'),
Country(name: 'Costa Rica'),
Country(name: 'Croatia'),
Country(name: 'Cuba'),
Country(name: 'Cyprus'),
Country(name: 'Czech Republic'),
Country(name: 'Denmark'),
Country(name: 'Djibouti'),
Country(name: 'Dominica'),
Country(name: 'Dominican Republic'),
Country(name: 'DR Congo'),
Country(name: 'Ecuador'),
Country(name: 'Egypt'),
Country(name: 'El Salvador'),
Country(name: 'Equatorial Guinea'),
Country(name: 'Eritrea'),
Country(name: 'Estonia'),
Country(name: 'Eswatini'),
Country(name: 'Ethiopia'),
Country(name: 'Fiji'),
Country(name: 'Finland'),
Country(name: 'France'),
Country(name: 'Gabon'),
Country(name: 'Gambia'),
Country(name: 'Georgia'),
Country(name: 'Germany'),
Country(name: 'Ghana'),
Country(name: 'Greece'),
Country(name: 'Grenada'),
Country(name: 'Guatemala'),
Country(name: 'Guinea'),
Country(name: 'Guinea-Bissau'),
Country(name: 'Guyana'),
Country(name: 'Haiti'),
Country(name: 'Honduras'),
Country(name: 'Hungary'),
Country(name: 'Iceland'),
Country(name: 'India'),
Country(name: 'Indonesia'),
Country(name: 'Iran'),
Country(name: 'Iraq'),
Country(name: 'Ireland'),
Country(name: 'Israel'),
Country(name: 'Italy'),
Country(name: 'Ivory Coast'),
Country(name: 'Jamaica'),
Country(name: 'Japan'),
Country(name: 'Jordan'),
Country(name: 'Kazakhstan'),
Country(name: 'Kenya'),
Country(name: 'Kiribati'),
Country(name: 'Kuwait'),
Country(name: 'Kyrgyzstan'),
Country(name: 'Laos'),
Country(name: 'Latvia'),
Country(name: 'Lebanon'),
Country(name: 'Lesotho'),
Country(name: 'Liberia'),
Country(name: 'Libya'),
Country(name: 'Liechtenstein'),
Country(name: 'Lithuania'),
Country(name: 'Luxembourg'),
Country(name: 'Madagascar'),
Country(name: 'Malawi'),
Country(name: 'Malaysia'),
Country(name: 'Maldives'),
Country(name: 'Mali'),
Country(name: 'Malta'),
Country(name: 'Marshall Islands'),
Country(name: 'Mauritania'),
Country(name: 'Mauritius'),
Country(name: 'Mexico'),
Country(name: 'Micronesia'),
Country(name: 'Moldova'),
Country(name: 'Monaco'),
Country(name: 'Mongolia'),
Country(name: 'Montenegro'),
Country(name: 'Morocco'),
Country(name: 'Mozambique'),
Country(name: 'Myanmar'),
Country(name: 'Namibia'),
Country(name: 'Nauru'),
Country(name: 'Nepal'),
Country(name: 'Netherlands'),
Country(name: 'New Zealand'),
Country(name: 'Nicaragua'),
Country(name: 'Niger'),
Country(name: 'Nigeria'),
Country(name: 'North Korea'),
Country(name: 'North Macedonia'),
Country(name: 'Norway'),
Country(name: 'Oman'),
Country(name: 'Pakistan'),
Country(name: 'Palau'),
Country(name: 'Palestine'),
Country(name: 'Panama'),
Country(name: 'Papua New Guinea'),
Country(name: 'Paraguay'),
Country(name: 'Peru'),
Country(name: 'Philippines'),
Country(name: 'Poland'),
Country(name: 'Portugal'),
Country(name: 'Qatar'),
Country(name: 'Romania'),
Country(name: 'Russia'),
Country(name: 'Rwanda'),
Country(name: 'Saint Kitts and Nevis'),
Country(name: 'Saint Lucia'),
Country(name: 'Saint Vincent and the Grenadines'),
Country(name: 'Samoa'),
Country(name: 'San Marino'),
Country(name: 'Sao Tome and Principe'),
Country(name: 'Saudi Arabia'),
Country(name: 'Senegal'),
Country(name: 'Serbia'),
Country(name: 'Seychelles'),
Country(name: 'Sierra Leone'),
Country(name: 'Singapore'),
Country(name: 'Slovakia'),
Country(name: 'Slovenia'),
Country(name: 'Solomon Islands'),
Country(name: 'Somalia'),
Country(name: 'South Africa'),
Country(name: 'South Korea'),
Country(name: 'South Sudan'),
Country(name: 'Spain'),
Country(name: 'Sri Lanka'),
Country(name: 'Sudan'),
Country(name: 'Suriname'),
Country(name: 'Sweden'),
Country(name: 'Switzerland'),
Country(name: 'Syria'),
Country(name: 'Taiwan'),
Country(name: 'Tajikistan'),
Country(name: 'Tanzania'),
Country(name: 'Thailand'),
Country(name: 'Timor-Leste'),
Country(name: 'Togo'),
Country(name: 'Tonga'),
Country(name: 'Trinidad and Tobago'),
Country(name: 'Tunisia'),
Country(name: 'Turkey'),
Country(name: 'Turkmenistan'),
Country(name: 'Tuvalu'),
Country(name: 'Uganda'),
Country(name: 'Ukraine'),
Country(name: 'United Arab Emirates'),
Country(name: 'United Kingdom'),
Country(name: 'United States'),
Country(name: 'Uruguay'),
Country(name: 'Uzbekistan'),
Country(name: 'Vanuatu'),
Country(name: 'Vatican City'),
Country(name: 'Venezuela'),
Country(name: 'Vietnam'),
Country(name: 'Yemen'),
Country(name: 'Zambia'),
Country(name: 'Zimbabwe'),
];
