// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6QAotrhep-3wX3cEfhZxX4rpOKlW_eio',
    appId: '1:628790831583:web:fce90d72855df6c227bc6a',
    messagingSenderId: '628790831583',
    projectId: 'habitapp-2e623',
    authDomain: 'habitapp-2e623.firebaseapp.com',
    storageBucket: 'habitapp-2e623.firebasestorage.app',
    measurementId: 'G-YVK7FCP1PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2iYL2vsIIg0VU8yys9hPmlV5JztEA3M',
    appId: '1:628790831583:android:1c542f537b6c96ff27bc6a',
    messagingSenderId: '628790831583',
    projectId: 'habitapp-2e623',
    storageBucket: 'habitapp-2e623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5VJz2uOIImUvNaR9oEypzfn8w2Qxy31M',
    appId: '1:628790831583:ios:0686406b360c966e27bc6a',
    messagingSenderId: '628790831583',
    projectId: 'habitapp-2e623',
    storageBucket: 'habitapp-2e623.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );
}
